{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kite.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kite.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ required "jwtSecret is required" .Values.jwtSecret | b64enc | quote }}
  KITE_ENCRYPT_KEY: {{ required "encryptKey is required" .Values.encryptKey | b64enc | quote }}
  REALMROOT_CLIENT_ID: {{ required "realmroot.clientId is required" .Values.realmroot.clientId | b64enc | quote }}
  REALMROOT_CLIENT_SECRET: {{ required "realmroot.clientSecret is required" .Values.realmroot.clientSecret | b64enc | quote }}
  {{- if ne .Values.db.type "sqlite" }}
  DB_TYPE: {{ .Values.db.type | b64enc | quote }}
  DB_DSN: {{ .Values.db.dsn | b64enc | quote }}
  {{- end }}
{{- end }}
