{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kite.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kite.labels" . | nindent 4 }}
type: Opaque
data:
  KITE_ENCRYPT_KEY: {{ required "encryptKey is required" .Values.encryptKey | b64enc | quote }}
  OIDC_CLIENT_ID: {{ required "oidc.clientId is required" .Values.oidc.clientId | b64enc | quote }}
  {{- with .Values.oidc.clientSecret }}
  OIDC_CLIENT_SECRET: {{ . | b64enc | quote }}
  {{- end }}
  {{- if ne .Values.db.type "sqlite" }}
  DB_DSN: {{ required "db.dsn is required for PostgreSQL and MySQL" .Values.db.dsn | b64enc | quote }}
  {{- end }}
{{- end }}
