{{- if and .Values.config.enabled (not .Values.config.existingSecret) }}
{{- $cfg := omit .Values.config "enabled" "existingSecret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lightkite.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lightkite.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    {{- with $cfg }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
