kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kite-realmroot-demo
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            oidc-issuer-url: https://id.realmroot.dev/api/auth
            oidc-client-id: 01a01b7c-0e17-70ac-9d46-15be8f82d1c0
            oidc-username-claim: email
            oidc-groups-claim: groups
